### ISSUE TITLE
能否获取历史战绩

### ISSUE THREAD

**Issue by Tianqi-Dotes** [dongwudi/ydzy#2]
你好我想咨询一下tft 云顶之弈
是否可以获取他的历史战绩数据？ 任何api（官方/非官方）
我看了一下拳头的是没有cn地区的
不过拳头的api倒是挺充分的数据
如果拳头的不行 估计只能抓腾讯自己的包了

谢谢

**Comment by liulxin** [comment]
腾讯的app是禁止抓包的好像。你可以试试看，我之前试的是不行的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 中午1:39
收件人:&nbsp;"liulxin/ydzy"<ydzy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[liulxin/ydzy] 能否获取历史战绩 (#2)




你好我想咨询一下tft 云顶之弈
 是否可以获取他的历史战绩数据？ 任何api（官方/非官方）
 我看了一下拳头的是没有cn地区的
 不过拳头的api倒是挺充分的数据
 如果拳头的不行 估计只能抓腾讯自己的包了
 
谢谢

**Comment by terrobladeD** [comment]
您好 我之前尝试过抓掌上英雄联盟的包 是可以获取战绩的 但是没法实现自动获取 您可以尝试一下 因为本人对逆向完全不通 感觉上是要稍微分析一下app的 愿和作者交流 谢谢
![1](https://user-images.githubusercontent.com/60980457/74358819-11dd4580-4dfd-11ea-83b2-9b5c54feb60e.png)

**Comment by NNanfeng** [comment]
> 您好 我之前尝试过抓掌上英雄联盟的包 是可以获取战绩的 但是没法实现自动获取 您可以尝试一下 因为本人对逆向完全不通 感觉上是要稍微分析一下app的 愿和作者交流 谢谢 ![1](https://user-images.githubusercontent.com/60980457/74358819-11dd4580-4dfd-11ea-83b2-9b5c54feb60e.png)
您好，请问您可以提供一下您抓到的掌盟的流量包吗，我想做一下战绩检测的功能，我的邮箱是1064888862@qq.com，如果可以的话，劳烦您了
